### ISSUE TITLE
我需要实施项目的帮助

### ISSUE THREAD

**Issue by fiftytwo52** [AES0P/TSCREEN#1]
大佬,你好
我是ABAP的一位开发人员.我对您的TSCREEN项目非常感兴趣,并且尝试想要在沙箱系统运行.但是我遇到了困难.
1.readme文件的信息非常少,以致我不是太清楚如何配置这些文件.
2.我观察到大部分信息都是以xml形式存在的,请问是否有相应的工具,能帮助我做到快速的下载SAP对象到本地,如果可能的话,能实现上传是最好的.
以上是我对项目配置方面的疑问,希望能得到您的帮助,非常感谢.
您可以联系我的QQ:2817215041;或者微信:KevinW15850076059

**Comment by AES0P** [comment]
你好，使用abapgit即可。
参考https://github.com/AES0P/TALV的readme相关部分。

**Comment by AES0P** [comment]
你好，使用abapgit即可。
参考 https://github.com/AES0P/TALV 的readme相关部分。

**Comment by fiftytwo52** [comment]
非常感谢您的帮助，谢谢
